/*
  Set any config.h overrides for your specific keymap here.
  See config.h options at https://docs.qmk.fm/#/config_options?id=the-configh-file
*/
#pragma once

#include "mem_squeeze.h"

#undef DYNAMIC_MACRO_SIZE
#define DYNAMIC_MACRO_SIZE 32

#undef  TAPPING_TERM
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY

#define DANCING_TERM 235

#undef  DEBOUNCE
#define DEBOUNCE 3

#undef  DEBOUNCE_TYPE
#define DEBOUNCE_TYPE = sym_defer_pk

#undef  IGNORE_MOD_TAP_INTERRUPT

#undef  FORCE_NKRO
#define FORCE_NKRO

#undef  TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#define PERMISSIVE_HOLD

#define ONESHOT_TAP_TOGGLE 2

#undef  ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 2000

#define RGB_DISABLE_WHEN_USB_SUSPENDED

#undef LED_BRIGHTNESS_DEFAULT
#define LED_BRIGHTNESS_DEFAULT (LED_BRIGHTNESS_LO)

#undef BACKLIGHT_PIN
#define BACKLIGHT_PIN D7

#undef BACKLIGHT_LEVELS
#define BACKLIGHT_LEVELS 31

#undef BACKLIGHT_BREATHING
#define BACKLIGHT_BREATHING

#undef BREATHING_PERIOD
#define BREATHING_PERIOD 6

#undef  MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 10

#undef  MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 15

#undef  MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 20

#undef  MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 200

#undef  MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 20

#undef  MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 200

#define USB_POLLING_INTERVAL_MS 1 // 1000Hz polling

#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_TAB
#define NO_AUTO_SHIFT_SYMBOLS
#define NO_AUTO_SHIFT_NUMERIC
#undef AUTO_SHIFT_ENTER
